DEVICE_PATH := device/nokia/lumia800

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := scorpion

TARGET_BOARD_PLATFORM := msm7x30
TARGET_BOOTLOADER_BOARD_NAME := msm8x55
BOARD_USES_QCOM_HARDWARE := true
TARGET_USES_QCOM_BSP := true

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/zImage

BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_PAGESIZE := 2048

BOARD_KERNEL_CMDLINE := androidboot.hardware=lumia800 androidboot.console=ttyMSM1 console=ttyMSM1,115200n8 loglevel=8 printk.time=1

# LK v0.12 FAT loader currently limits LINUX.IMG to 24 MiB.
BOARD_BOOTIMAGE_PARTITION_SIZE := 25165824
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_USERIMAGES_USE_EXT4 := true

# Virtual build sizes only. DO NOT flash these images to current Lumia partitions.
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 671088640
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456

TARGET_SCREEN_WIDTH := 480
TARGET_SCREEN_HEIGHT := 800
TARGET_SCREEN_DENSITY := 240

USE_CAMERA_STUB := true
BOARD_HAVE_BLUETOOTH := false
BOARD_HAS_NO_SELECT_BUTTON := true

WITH_DEXPREOPT := false
